// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Formulario_Registro', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1376, height: 784 })
    await driver.findElement(By.css(".rounded")).click()
    await driver.findElement(By.linkText("Registrarse")).click()
    await driver.findElement(By.id("firstName")).click()
    await driver.findElement(By.id("firstName")).sendKeys("Yohana")
    await driver.findElement(By.id("lastName")).click()
    await driver.findElement(By.id("lastName")).sendKeys("Zapata")
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("yohaskj22")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("yohaskj22@gmail.com")
    await driver.findElement(By.id("phone")).click()
    await driver.findElement(By.id("phone")).sendKeys("3137346713")
    await driver.findElement(By.id("documentNumber")).click()
    await driver.findElement(By.id("documentNumber")).sendKeys("1130681593")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("YOHAnaz1*")
    await driver.findElement(By.id("confirmPassword")).click()
    await driver.findElement(By.id("confirmPassword")).sendKeys("YOHAnaz1*")
    await driver.findElement(By.css(".w-40")).click()
    assert(await driver.findElement(By.css(".text-red-500")).getText() == "La contraseña debe tener al menos 8 caracteres, incluyendo un número, una letra mayúscula, una letra minúscula y un carácter especial (@#.$%^&+=!)")
    await driver.findElement(By.css(".min-h-screen")).click()
    await driver.findElement(By.css(".space-y-8")).click()
  })
  it('InicioSesion', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1376, height: 784 })
    await driver.findElement(By.css(".rounded")).click()
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("yohaskj22")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("yohas123")
    await driver.findElement(By.css(".w-40")).click()
  })
})
