server:
  #port: ${PORT:${SERVER_PORT:0}}
  port: 8080

spring:
  application:
    name: ms-cart
  datasource:
    #url: jdbc:mysql://localhost:3306/mscart
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/mscart
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mysql:
    console:
      enabled: true

#eureka:
#  instance:
#    hostname: localhost
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    service-url:
#      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      #default-zone: http://localhost:8761/eureka
      defaultZone: http://ms-discovery:8761/eureka/
    instance:
      prefer-ip-address: false
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 10

management:
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info

info:
  app:
    name: ms-cart
    description: ms-cart
    version: 1.0.0



resilience4j:
  circuitbreaker:
    instances:
      productService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true


  retry:
    instances:
      productService:
        waitDuration: 1000
        maxAttempts: 3
        retryExceptions:
          - feign.FeignException$InternalServerError



